#! /bin/sh

sxhkd &
rofi  &
compton &
polybar_lunch &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config window_gap          13
bspc config top_padding         0
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

BLACk="#0d0d0d"
WHITE1="#b9b9b9"
WHITE2="#f7f7f7"
DARK_GRAY="#686868"
LIGHT_GRAY="#8e8e8e"
DARK_TEAL="#00897b"

# color
bspc config focused_border_color $WHITE2
bspc config normal_border_color  $DARK_GRAY
bspc config presel_border_color "#8F3724"
bspc config urgent_border_color "#504339"
bspc config focused_private_border_color "#35BF5C"